#!/bin/bash

echo "########## GIT INSTALLATION & CONFIGURATION ##########"
sudo apt-get install git-core
git config --global color.diff auto
git config --global color.status auto
git config --global color.branch auto
git config --global push.default matching
git config --global user.name "$1"
git config --global user.email $2

echo "########## SSH KEYGEN CREATION ##########"
ssh-keygen -t rsa -C "$2"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub

echo "########## PIP & DJANGO INSTALLATION ##########"
sudo apt-get install python-pip python-dev build-essential
sudo pip install --upgrade pip
sudo pip install Django
echo "Django version :"
python -c "import django; print django.get_version()"

# echo "########## INIT REPERTORY SMELLGAME ##########"
# django-admin.py startproject SmellGame
# cd SmellGame
# python manage.py startapp formapp
# touch README.md
# git init
# git commit -a
# git remote add origin git@github.com:JeanCoq/SmellGame.git
# git push -u origin master

echo "########## CLONE REPERTORY SMELLGAME ##########"
cd $3
git clone git@github.com:JeanCoq/SmellGame.git